//
//  UserRouter.swift
//  UserList
//
//  Created Apple on 4/7/20.
//  Copyright © 2020 VNPay. All rights reserved.
//
//  Template generated by @thetay
//

import UIKit

protocol UserRouting: Routing {
    // Declare methods the interactor can invoke to manage sub-tree via the router.
}

final class UserRouter<ViewControllerType>:UserRouting{
  
  public let uiviewController: ViewControllerType
  
  public init(viewController: ViewControllerType) {
      self.uiviewController = viewController
  }
  
   
}

