//
//  UserWorker.swift
//  UserList
//
//  Created Apple on 4/7/20.
//  Copyright © 2020 VNPay. All rights reserved.
//
//  Template generated by Vnpay
//
import Foundation
import Alamofire
let ApiBaseURl = "https://api.github.com/search/users?q="

protocol UserAPIWorkerProtocol {
  func fetchUser(username:String,callBack:@escaping(UserRequest?)->Void)
}
final class UserWorker:UserAPIWorkerProtocol {
  func fetchUser(username: String, callBack: @escaping (UserRequest?) -> Void) {
    
    Alamofire.request(ApiBaseURl+username).responseJSON { (response) in
      
      if let error = response.error{
        debugPrint(error.localizedDescription)
        callBack(nil)
      }
      
      guard let data = response.data else {return callBack(nil)}
      let jsonDecoder = JSONDecoder()
      
      do {
        let person = try jsonDecoder.decode(UserRequest.self, from: data)
        callBack(person)
      } catch {
        debugPrint(error.localizedDescription)
        callBack(nil)
      }
      
    }
    
  }
  
  
  
}
